import OnboardingScreen1 from "./OnboardingScreen1";
import OnboardingScreen2 from "./OnboardingScreen2";    
import OnboardingScreen3 from "./OnboardingScreen3";
import Splash from "./Splash";
import Login from "./Login";
import Home from "./Home";
import Statistik from "./Statistik";
import Location from "./Location";
import InputData from "./InputData";
import ListData from "./ListData";
export {OnboardingScreen1, OnboardingScreen2, OnboardingScreen3, Splash, Login, Home, Statistik, Location, InputData, ListData}; 
